### PR TITLE
rename pew3wm package to consistent py3status-pewpew (fix #15)

### LINKED ISSUE #15: Package name still legacy "pew3wm"
Noticed repository changed name to `py3status-pewpew` nice @obestwalter 

Any particular reason why setup.py still uses the, now legacy, name "pew3wm" (other than nostalgia! heh)?

### PR DESCRIPTION
**Pull request by ultrabug**

### CODE REVIEW

**Comment by ultrabug** [comment]
@obestwalter @objarni 

I'm suddenly asking myself if a good practice could be to propose the package name to be the owner's name of the repo / pypi package

In our case here : `obestwalter.pewpew` ?

**Comment by objarni** [comment]
@ultrabug one consequence would be that the 'maintainer' of the package/plugin is more prominent, for good or bad... Literally part of the name!

Another consequence would be that it would feel more natural to do your own 'flavor' of a plugin, it would even be possible to install several plugins of same "module" in parallell in one virtual environment. It would make the 'friction' involved in coming up with a name a lot less also.

A potential downside would be that 'ownership' would be very strong with that naming convention, and code ownership is kind of against much of modern s/w dev practice since decades now, thinking of agile "everyone owns all code", avoiding code islands/hogring. (But I'm having a hard time seeing this argument being valid in the context of smallish plugins for py3status! We're not talking enterprise software systems here!)

What line of thought made you arrive at the idea @ultrabug ?

**Comment by objarni** [comment]
I tested this PR by removing build/ dist/ and .tox/ folders, then `tox` (green), then searched for `pew3wm` in all files. 0 hits so I guess the new name is a fact. If we want to change the naming convention maybe we should do it in a separate issue / PR..?

**Comment by objarni** [comment]
Not sure why there is a conflict in this PR. And too tired to figure out why right now :)

**Comment by ultrabug** [comment]
> What line of thought made you arrive at the idea @ultrabug ?

Mainly the fact that I dislike the `py3status_pewpew` naming... and tried to find a simple yet efficient way to name the modules because actually we do not use / see the first part of the name and py3status only cares about the second part (pewpew) which is the actual module name

**Comment by ultrabug** [comment]
> Not sure why there is a conflict in this PR. And too tired to figure out why right now :)

Because I merged yours before, that's fine, I'll rebase once we agree on the name

**Comment by objarni** [comment]
Ah, I see.

If dots are permitted in package names, I guess `py3status.pewpew` would be another option?

However, I find your naming convention/idea more interesting :)

What does @obestwalter think on this subject?

**Comment by obestwalter** [comment]
I don't really feel the maintainer of the package belongs into the name. To start with: who's the maintainer of this one? I mean o.k. I created the repo, but it was a group effort from the start and several people have the commit bit already. When I made the first release at least one of you should also have release rights (@objarni ?). Maintainers also change over time, so I'd propose to stick with the current scheme.

As this project is basically a plugin for py3status, I think py3status-pewpew is the naturally correct name. It is the same scheme that other tools use (e.g. pytest plugins are called `pytest-whatever`), so we are just following a well established convention here.

@ultrabug: if you are worried about maintenance burden from plugins due to pure name association it might be a good idea to mention that explicitly in the docs that thos plugins are maintained by their respective maintainers (sometimes it's necessary to say the obvious).

I have some time tonight later to make a release if we can sort this out, otherwise it will likely have to wait until next week, as I am at a music festival from tomorrow on. So I have to start packing now :)

**Comment by obestwalter** [comment]
I tidied everything up and go packing now, will check later tonight, if we can release as "py3status-pewpew" then :)

**Comment by obestwalter** [comment]
@ultrabug hope it's ok I cleaned up a bit and straightened out the naming. The way it is now it what is widely used. package names on PYPi normally use hyphens and Python package names use underscore as separator.

**Comment by ultrabug** [comment]
@obestwalter thanks for this and for your input, that's perfect for me :+1:

**Comment by obestwalter** [comment]
ok - package is out. Added a license and classifiers for PyPI

A bit rough around the edges still but good enough as a 0.a alpha to play around with :)

I might do a post release with at least the project url and the readme as long description if I still have a little time later.

Also: I am not sure if "EuroPython py3status pewpew" is an adequate copyright holder :)

**Comment by obestwalter** [comment]
Couldn't let that slip, so released a new package now: https://pypi.org/project/py3status-pewpew/0.1.post1/

**Comment by objarni** [comment]
Great @obestwalter!! I'll try and do an end-to-end test with a new virtualenv asap!

**Comment by objarni** [comment]
image

Is py3status supposed to be a dependency of py3status-pewpew (I was expecting that)? It does not seem to be that ATM.

**Comment by objarni** [comment]
.. and after `pip install py3status` we get a working installation! Wo-hoo!

image

Notice v3.20 of py3status, and that I did Ctrl+Mod+R to ensure reloading of py3status process (it was showing the red error before installing py3status in the venv).

**Comment by ultrabug** [comment]
Like a pro! Awesome, thanks a lot guys... I'm amazed about this

I will write a blog post too to share about this experience

**Comment by obestwalter** [comment]
> Is py3status supposed to be a dependency of py3status-pewpew (I was expecting that)? It does not seem to be that ATM.

Right. And specifically >=3.20 - released 0.2 just now.

**Comment by objarni** [comment]
Tested in fresh env. Works!

**Comment by ultrabug** [comment]
idem, thanks!

**Pull request merged**
